// Generated test data for Retail AI Showcase US-market sandbox.
// Prices/names are realistic demo data, not live retailer stock.

import type { Product } from '../types';

export const products: Product[] = [
  {
    "id": "veg-001",
    "name": "Baby Potatoes",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 4.19,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "1.5 lb bag",
    "image": "/images/products/veg-001.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "baby potatoes",
      "produce",
      "fresh vegetables",
      "vegetables",
      "baby",
      "potatoes"
    ],
    "description": "Small, thin-skinned potatoes with a creamy texture, ideal for roasting, boiling, and salads.",
    "brand": null
  },
  {
    "id": "veg-002",
    "name": "Carrots",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 2.29,
    "oldPrice": 2.79,
    "unit": "pack",
    "packageSize": "2 lb bag",
    "image": "/images/products/veg-002.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "carrots",
      "produce",
      "fresh vegetables",
      "fresh carrots",
      "vegetables"
    ],
    "description": "Fresh carrots for roasting, soups, salads, and everyday cooking.",
    "brand": null
  },
  {
    "id": "veg-003",
    "name": "Beets",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 1.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "1 lb",
    "image": "/images/products/veg-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "beets",
      "produce",
      "fresh vegetables",
      "vegetables"
    ],
    "description": "Fresh beets with an earthy, slightly sweet flavor for roasting, soups, and salads.",
    "brand": null
  },
  {
    "id": "veg-004",
    "name": "Green Cabbage",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 head",
    "image": "/images/products/veg-004.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "green cabbage",
      "produce",
      "fresh vegetables",
      "vegetables",
      "cabbage",
      "green"
    ],
    "description": "Crisp green cabbage for slaws, soups, braises, and stir-fries.",
    "brand": null
  },
  {
    "id": "veg-005",
    "name": "Onions",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 3.69,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "3 lb bag",
    "image": "/images/products/veg-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "onions",
      "produce",
      "fresh vegetables",
      "vegetables"
    ],
    "description": "Versatile onions for soups, sauces, sautéing, roasting, and everyday cooking.",
    "brand": null
  },
  {
    "id": "veg-006",
    "name": "Garlic",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 1.49,
    "oldPrice": 1.79,
    "unit": "pack",
    "packageSize": "3 ct",
    "image": "/images/products/veg-006.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "garlic",
      "produce",
      "fresh vegetables",
      "fresh garlic",
      "vegetables"
    ],
    "description": "Fresh garlic for sauces, marinades, roasting, and seasoning.",
    "brand": null
  },
  {
    "id": "veg-007",
    "name": "Pink Tomatoes",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "1 lb",
    "image": "/images/products/veg-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "pink tomatoes",
      "produce",
      "fresh vegetables",
      "vegetables",
      "pink",
      "tomatoes"
    ],
    "description": "Juicy pink tomatoes for salads, sandwiches, and fresh dishes.",
    "brand": null
  },
  {
    "id": "veg-008",
    "name": "Cucumbers",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 0.89,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 ct",
    "image": "/images/products/veg-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "cucumbers",
      "produce",
      "fresh vegetables",
      "fresh cucumbers",
      "vegetables"
    ],
    "description": "Fresh cucumbers with a crisp texture for salads, sandwiches, and snacking.",
    "brand": null
  },
  {
    "id": "veg-009",
    "name": "Red Bell Peppers",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 3.99,
    "oldPrice": 4.49,
    "unit": "pack",
    "packageSize": "3 ct",
    "image": "/images/products/veg-009.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "red bell peppers",
      "produce",
      "fresh vegetables",
      "vegetables",
      "bell",
      "peppers",
      "red"
    ],
    "description": "Sweet red bell peppers for salads, roasting, stuffing, and sautéing.",
    "brand": null
  },
  {
    "id": "veg-010",
    "name": "Zucchini",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Vegetables",
    "price": 1.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "2 ct",
    "image": "/images/products/veg-010.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "zucchini",
      "produce",
      "fresh vegetables",
      "vegetables"
    ],
    "description": "Fresh zucchini for grilling, roasting, sautéing, and baking.",
    "brand": null
  },
  {
    "id": "veg-011",
    "name": "Dill",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Herbs",
    "price": 1.29,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 bunch",
    "image": "/images/products/veg-011.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "dill",
      "produce",
      "fresh herbs",
      "fresh dill"
    ],
    "description": "Fresh dill with a bright herbal flavor for salads, potatoes, seafood, and sauces.",
    "brand": null
  },
  {
    "id": "veg-012",
    "name": "Parsley",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Herbs",
    "price": 1.19,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 bunch",
    "image": "/images/products/veg-012.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "parsley",
      "produce",
      "fresh herbs",
      "fresh parsley"
    ],
    "description": "Fresh parsley for garnishing, salads, sauces, soups, and everyday cooking.",
    "brand": null
  },
  {
    "id": "veg-013",
    "name": "Red Apples",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Fruit",
    "price": 4.99,
    "oldPrice": 5.49,
    "unit": "pack",
    "packageSize": "3 lb bag",
    "image": "/images/products/veg-013.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "red apples",
      "produce",
      "fresh fruit",
      "fruit",
      "apples",
      "red"
    ],
    "description": "Crisp red apples for snacking, baking, and lunchboxes.",
    "brand": null
  },
  {
    "id": "veg-014",
    "name": "Bananas",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Fruit",
    "price": 1.49,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 bunch",
    "image": "/images/products/veg-014.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "bananas",
      "produce",
      "fresh fruit",
      "fruit"
    ],
    "description": "Ripe bananas for snacking, breakfast, smoothies, and baking.",
    "brand": null
  },
  {
    "id": "veg-015",
    "name": "Lemon",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Fruit",
    "price": 0.69,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 ct",
    "image": "/images/products/veg-015.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "lemon",
      "produce",
      "fresh fruit",
      "fruit"
    ],
    "description": "Fresh lemon for drinks, dressings, marinades, baking, and finishing dishes.",
    "brand": null
  },
  {
    "id": "veg-016",
    "name": "Oranges",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Fruit",
    "price": 4.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "3 lb bag",
    "image": "/images/products/veg-016.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "oranges",
      "produce",
      "fresh fruit",
      "fruit"
    ],
    "description": "Juicy oranges for snacking, breakfast, and fresh juice.",
    "brand": null
  },
  {
    "id": "veg-017",
    "name": "Avocado",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Fruit",
    "price": 0.79,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 ct",
    "image": "/images/products/veg-017.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "avocado",
      "produce",
      "fresh fruit",
      "fruit"
    ],
    "description": "Ripe avocado for toast, salads, sandwiches, guacamole, and bowls.",
    "brand": null
  },
  {
    "id": "veg-018",
    "name": "White Mushrooms",
    "category": "Produce",
    "categorySlug": "ovochi-frukty",
    "subcategory": "Fresh Mushrooms",
    "price": 1.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/veg-018.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "white mushrooms",
      "produce",
      "fresh mushrooms",
      "white button mushrooms",
      "mushrooms",
      "button",
      "white"
    ],
    "description": "Fresh white button mushrooms for sautéing, soups, sauces, and roasting.",
    "brand": null
  },
  {
    "id": "meat-001",
    "name": "Boneless Skinless Chicken Breasts",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Chicken",
    "price": 7.49,
    "oldPrice": 8.49,
    "unit": "pack",
    "packageSize": "3 lb tray",
    "image": "/images/products/meat-001.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "boneless skinless chicken breasts",
      "meat & poultry",
      "chicken",
      "poultry",
      "breast",
      "boneless",
      "skinless"
    ],
    "description": "Lean boneless, skinless chicken breasts for grilling, baking, sautéing, and meal prep.",
    "brand": null
  },
  {
    "id": "meat-002",
    "name": "Chicken Thighs",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Chicken",
    "price": 6.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "3 lb tray",
    "image": "/images/products/meat-002.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "chicken thighs",
      "meat & poultry",
      "chicken",
      "poultry",
      "thighs"
    ],
    "description": "Chicken thighs with rich flavor for roasting, grilling, braising, and weeknight meals.",
    "brand": null
  },
  {
    "id": "meat-003",
    "name": "Chicken Drumsticks",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Chicken",
    "price": 4.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "3 lb tray",
    "image": "/images/products/meat-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "chicken drumsticks",
      "meat & poultry",
      "chicken",
      "poultry",
      "drumsticks"
    ],
    "description": "Chicken drumsticks for roasting, grilling, braising, and family meals.",
    "brand": null
  },
  {
    "id": "meat-004",
    "name": "Whole Chicken",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Chicken",
    "price": 8.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "about 5 lb",
    "image": "/images/products/meat-004.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "whole chicken",
      "meat & poultry",
      "chicken",
      "poultry",
      "whole"
    ],
    "description": "Whole chicken for roasting, grilling, soups, and family meals.",
    "brand": null
  },
  {
    "id": "meat-005",
    "name": "Pork Shoulder Roast",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Pork",
    "price": 9.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "4 lb",
    "image": "/images/products/meat-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "pork shoulder roast",
      "meat & poultry",
      "pork",
      "pork shoulder",
      "shoulder",
      "roast"
    ],
    "description": "Pork shoulder roast with rich marbling, ideal for slow roasting, braising, and pulled pork.",
    "brand": null
  },
  {
    "id": "meat-006",
    "name": "Pork Neck",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Pork",
    "price": 11.99,
    "oldPrice": 13.49,
    "unit": "pack",
    "packageSize": "2 lb pack",
    "image": "/images/products/meat-006.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "pork neck",
      "meat & poultry",
      "pork",
      "neck"
    ],
    "description": "Pork neck with rich flavor for slow cooking, braising, stews, and soups.",
    "brand": null
  },
  {
    "id": "meat-007",
    "name": "Ground Beef & Pork Blend",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Ground Meat",
    "price": 4.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "1 lb",
    "image": "/images/products/meat-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "ground beef & pork blend",
      "meat & poultry",
      "ground meat",
      "beef",
      "pork",
      "blend",
      "ground"
    ],
    "description": "A ground beef and pork blend for meatballs, burgers, dumplings, and sauces.",
    "brand": null
  },
  {
    "id": "meat-008",
    "name": "Hot Dog Franks",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Deli Meat & Sausages",
    "price": 5.49,
    "oldPrice": 6.29,
    "unit": "pack",
    "packageSize": "14 oz",
    "image": "/images/products/meat-008.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "hot dog franks",
      "franks",
      "hot dogs",
      "sausages",
      "quick dinner",
      "grilling"
    ],
    "description": "Fully cooked franks with a mild flavor for hot dogs, grilling, and quick meals.",
    "brand": null
  },
  {
    "id": "meat-009",
    "name": "Bologna",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Deli Meat & Sausages",
    "price": 5.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "1 lb",
    "image": "/images/products/meat-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "bologna",
      "deli meat",
      "sandwich meat",
      "cold cuts"
    ],
    "description": "Mild bologna for sandwiches, cold-cut platters, and quick lunches.",
    "brand": null
  },
  {
    "id": "meat-010",
    "name": "Sliced Chicken Deli Meat",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Deli Meat & Sausages",
    "price": 4.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "9 oz",
    "image": "/images/products/meat-010.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "sliced chicken deli meat",
      "meat & poultry",
      "deli meat & sausages",
      "sausage & deli meat",
      "chicken",
      "deli",
      "meat",
      "sliced"
    ],
    "description": "Sliced chicken deli meat for sandwiches, wraps, salads, and quick lunches.",
    "brand": null
  },
  {
    "id": "meat-011",
    "name": "Salami",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Deli Meat & Sausages",
    "price": 5.49,
    "oldPrice": 6.49,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/meat-011.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "salami",
      "meat & poultry",
      "deli meat & sausages",
      "sausage & deli meat"
    ],
    "description": "Ready-to-eat salami for sandwiches, charcuterie boards, and snacks.",
    "brand": null
  },
  {
    "id": "meat-012",
    "name": "Sliced Bacon",
    "category": "Meat & Poultry",
    "categorySlug": "miaso-ptytsia",
    "subcategory": "Deli Meat & Sausages",
    "price": 4.29,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "12 oz",
    "image": "/images/products/meat-012.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "sliced bacon",
      "meat & poultry",
      "deli meat & sausages",
      "sausage & deli meat",
      "bacon",
      "sliced"
    ],
    "description": "Sliced bacon for breakfast, sandwiches, burgers, and cooking.",
    "brand": null
  },
  {
    "id": "dairy-001",
    "name": "2% Reduced Fat Milk",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Milk",
    "price": 2.18,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "64 fl oz",
    "image": "/images/products/dairy-001.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "2% milk",
      "reduced fat milk",
      "milk",
      "dairy",
      "breakfast",
      "cereal"
    ],
    "description": "Reduced-fat milk for cereal, coffee, cooking, and everyday drinking.",
    "brand": null
  },
  {
    "id": "dairy-002",
    "name": "Shelf-Stable 2% Milk",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Milk",
    "price": 3.44,
    "oldPrice": 3.84,
    "unit": "pack",
    "packageSize": "32 fl oz",
    "image": "/images/products/dairy-002.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "shelf-stable milk",
      "2% milk",
      "uht milk",
      "pantry milk",
      "dairy"
    ],
    "description": "Shelf-stable reduced-fat milk for the pantry, coffee, cereal, and cooking.",
    "brand": null
  },
  {
    "id": "dairy-003",
    "name": "Cultured Cream, 15% Milkfat",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Sour Cream",
    "price": 1.84,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/dairy-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "cultured cream, 15% milkfat",
      "sour cream",
      "dairy",
      "dip",
      "tacos",
      "baked potato"
    ],
    "description": "Tangy cultured cream with 15% milkfat for savory dishes, dips, and serving.",
    "brand": null
  },
  {
    "id": "dairy-004",
    "name": "Sour Cream",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Sour Cream",
    "price": 2.29,
    "oldPrice": 2.64,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/dairy-004.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "sour cream",
      "dairy",
      "dip",
      "baked potato",
      "cooking"
    ],
    "description": "Rich sour cream for dips, baked potatoes, soups, and cooking.",
    "brand": null
  },
  {
    "id": "dairy-005",
    "name": "Salted Butter",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Butter",
    "price": 4.46,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/dairy-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "salted butter",
      "butter",
      "dairy",
      "baking",
      "cooking"
    ],
    "description": "Salted butter for toast, cooking, baking, and finishing dishes.",
    "brand": null
  },
  {
    "id": "dairy-006",
    "name": "Gouda Cheese",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Cheese",
    "price": 3.98,
    "oldPrice": 4.49,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/dairy-006.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "gouda cheese",
      "gouda",
      "cheese",
      "dairy",
      "sandwiches",
      "snacks"
    ],
    "description": "Mild Gouda cheese for sandwiches, snacks, and melting.",
    "brand": null
  },
  {
    "id": "dairy-007",
    "name": "Farmer Cheese",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Fresh Cheese",
    "price": 5.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/dairy-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "farmer cheese",
      "fresh cheese",
      "dairy",
      "breakfast",
      "baking"
    ],
    "description": "Fresh farmer cheese for breakfast, baking, savory dishes, and desserts.",
    "brand": null
  },
  {
    "id": "dairy-008",
    "name": "Strawberry Drinkable Yogurt",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Yogurt",
    "price": 3.98,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "32 fl oz",
    "image": "/images/products/dairy-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "strawberry drinkable yogurt",
      "drinkable yogurt",
      "yogurt",
      "strawberry",
      "dairy",
      "breakfast"
    ],
    "description": "Smooth strawberry drinkable yogurt for breakfast or an on-the-go snack.",
    "brand": null
  },
  {
    "id": "dairy-009",
    "name": "Plain Kefir",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Kefir",
    "price": 3.84,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "32 fl oz",
    "image": "/images/products/dairy-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "plain kefir",
      "kefir",
      "cultured milk",
      "dairy",
      "breakfast",
      "smoothies"
    ],
    "description": "Plain cultured kefir with a tangy flavor for breakfast or smoothies.",
    "brand": null
  },
  {
    "id": "dairy-010",
    "name": "Large Eggs",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Eggs",
    "price": 1.49,
    "oldPrice": 1.99,
    "unit": "pack",
    "packageSize": "12 ct",
    "image": "/images/products/dairy-010.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "large eggs",
      "eggs",
      "dozen eggs",
      "breakfast",
      "baking"
    ],
    "description": "A dozen large eggs for breakfast, baking, and everyday cooking.",
    "brand": null
  },
  {
    "id": "dairy-011",
    "name": "Creamy Cheese Spread",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Cheese",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/dairy-011.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "cheese spread",
      "creamy cheese spread",
      "cheese",
      "spread",
      "snacks"
    ],
    "description": "Smooth cheese spread for toast, crackers, sandwiches, and snacks.",
    "brand": null
  },
  {
    "id": "dairy-012",
    "name": "Half & Half",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Cream & Half-and-Half",
    "price": 1.78,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 fl oz",
    "image": "/images/products/dairy-012.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "half & half",
      "half and half",
      "coffee creamer",
      "cream",
      "dairy",
      "coffee"
    ],
    "description": "Half & half for coffee, sauces, soups, and everyday cooking.",
    "brand": null
  },
  {
    "id": "dairy-013",
    "name": "Mozzarella Cheese",
    "category": "Dairy & Eggs",
    "categorySlug": "molochni-iaitsia",
    "subcategory": "Cheese",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/dairy-013.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "mozzarella cheese",
      "dairy & eggs",
      "cheese",
      "mozzarella"
    ],
    "description": "Mild mozzarella cheese for sandwiches, pizza, pasta, and melting.",
    "brand": null
  },
  {
    "id": "bakery-001",
    "name": "White Bread",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Bread",
    "price": 1.69,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "20 oz loaf",
    "image": "/images/products/bakery-001.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "white bread",
      "bakery & bread",
      "bread",
      "sliced white bread",
      "white"
    ],
    "description": "Soft white bread for toast, sandwiches, and everyday meals.",
    "brand": null
  },
  {
    "id": "bakery-002",
    "name": "Rye & Wheat Bread",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Bread",
    "price": 3.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "20 oz loaf",
    "image": "/images/products/bakery-002.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "rye & wheat bread",
      "bakery & bread",
      "bread",
      "rye",
      "wheat"
    ],
    "description": "Rye-and-wheat bread with a hearty flavor for toast and sandwiches.",
    "brand": null
  },
  {
    "id": "bakery-003",
    "name": "White Bread Loaf",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Bread",
    "price": 1.59,
    "oldPrice": 1.89,
    "unit": "pack",
    "packageSize": "20 oz loaf",
    "image": "/images/products/bakery-003.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "white bread loaf",
      "bakery & bread",
      "bread",
      "sliced white sandwich loaf",
      "sandwich",
      "loaf"
    ],
    "description": "A crusty white loaf with a soft crumb for slicing, sandwiches, and serving with meals.",
    "brand": null
  },
  {
    "id": "bakery-004",
    "name": "Lavash Flatbread",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Flatbreads",
    "price": 3.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "9 oz",
    "image": "/images/products/bakery-004.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "lavash flatbread",
      "bakery & bread",
      "flatbreads",
      "flatbread",
      "bread"
    ],
    "description": "Thin lavash flatbread for wraps, roll-ups, and serving with dips.",
    "brand": null
  },
  {
    "id": "bakery-005",
    "name": "Hamburger Buns",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Buns & Rolls",
    "price": 1.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 ct",
    "image": "/images/products/bakery-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "hamburger buns",
      "bakery & bread",
      "buns & rolls",
      "burger buns",
      "bread",
      "burger",
      "buns",
      "hamburger"
    ],
    "description": "Soft hamburger buns for burgers, sandwiches, and cookouts.",
    "brand": null
  },
  {
    "id": "bakery-006",
    "name": "Chocolate Croissant",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Pastries",
    "price": 1.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "3 oz",
    "image": "/images/products/bakery-006.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "chocolate croissant",
      "bakery & bread",
      "pastries",
      "bread",
      "chocolate",
      "croissant"
    ],
    "description": "Buttery pastry with a chocolate filling for breakfast or a sweet snack.",
    "brand": null
  },
  {
    "id": "bakery-007",
    "name": "Croutons",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Croutons",
    "price": 1.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "5 oz",
    "image": "/images/products/bakery-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "croutons",
      "bakery & bread",
      "wheat croutons",
      "bread",
      "wheat"
    ],
    "description": "Crisp croutons for salads, soups, and snacking.",
    "brand": null
  },
  {
    "id": "bakery-008",
    "name": "Palianytsia Bread",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Bread",
    "price": 4.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "24 oz loaf",
    "image": "/images/products/bakery-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "palianytsia bread",
      "palianytsia",
      "traditional bread",
      "artisan bread",
      "bread"
    ],
    "description": "Traditional palianytsia with a soft crumb and baked crust, served with soups and everyday meals.",
    "brand": null
  },
  {
    "id": "bakery-009",
    "name": "Homestyle White Bread",
    "category": "Bakery & Bread",
    "categorySlug": "khlib-vypichka",
    "subcategory": "Bread",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "20 oz loaf",
    "image": "/images/products/bakery-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "homestyle white bread",
      "bakery & bread",
      "bread",
      "white sandwich bread",
      "sandwich",
      "homestyle",
      "white"
    ],
    "description": "Soft homestyle white bread for toast and sandwiches.",
    "brand": null
  },
  {
    "id": "grocery-001",
    "name": "Fusilli",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Pasta",
    "price": 1.24,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/grocery-001.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "fusilli",
      "pantry",
      "pasta",
      "fusilli pasta",
      "cooking"
    ],
    "description": "Spiral-shaped fusilli pasta that holds sauces well in pasta dishes, salads, and casseroles.",
    "brand": null
  },
  {
    "id": "grocery-002",
    "name": "Spaghetti",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Pasta",
    "price": 1.24,
    "oldPrice": 1.49,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/grocery-002.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "spaghetti",
      "pantry",
      "pasta",
      "cooking"
    ],
    "description": "Spaghetti for tomato sauces, meat sauces, and simple pasta meals.",
    "brand": null
  },
  {
    "id": "grocery-003",
    "name": "Long-Grain Rice",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Rice & Grains",
    "price": 3.69,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "5 lb bag",
    "image": "/images/products/grocery-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "long-grain rice",
      "pantry",
      "rice & grains",
      "grains",
      "cooking",
      "long-grain",
      "rice"
    ],
    "description": "Long-grain rice with separate, fluffy grains for sides, pilafs, and everyday meals.",
    "brand": null
  },
  {
    "id": "grocery-004",
    "name": "Buckwheat Groats",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Rice & Grains",
    "price": 6.49,
    "oldPrice": 7.49,
    "unit": "pack",
    "packageSize": "2 lb bag",
    "image": "/images/products/grocery-004.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "buckwheat groats",
      "pantry",
      "rice & grains",
      "grains",
      "buckwheat",
      "cooking",
      "groats"
    ],
    "description": "Nutty buckwheat groats for porridge, grain bowls, sides, and Eastern European dishes.",
    "brand": null
  },
  {
    "id": "grocery-005",
    "name": "Rolled Oats",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Rice & Grains",
    "price": 4.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "42 oz",
    "image": "/images/products/grocery-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "rolled oats",
      "pantry",
      "rice & grains",
      "grains",
      "cooking",
      "rolled",
      "oats"
    ],
    "description": "Rolled oats for oatmeal, overnight oats, baking, and homemade granola.",
    "brand": null
  },
  {
    "id": "grocery-006",
    "name": "All-Purpose Flour",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Baking",
    "price": 2.39,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "5 lb bag",
    "image": "/images/products/grocery-006.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "all-purpose flour",
      "pantry",
      "baking",
      "wheat flour",
      "flour",
      "cooking",
      "wheat"
    ],
    "description": "All-purpose wheat flour for baking, sauces, breads, and everyday cooking.",
    "brand": null
  },
  {
    "id": "grocery-007",
    "name": "Granulated Sugar",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Baking",
    "price": 3.29,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "4 lb bag",
    "image": "/images/products/grocery-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "granulated sugar",
      "pantry",
      "baking",
      "sugar",
      "cooking",
      "granulated"
    ],
    "description": "Granulated sugar for baking, beverages, desserts, and everyday cooking.",
    "brand": null
  },
  {
    "id": "grocery-008",
    "name": "Table Salt",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Salt",
    "price": 0.89,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "26 oz",
    "image": "/images/products/grocery-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "table salt",
      "pantry",
      "salt",
      "cooking",
      "table"
    ],
    "description": "Fine table salt for cooking, baking, and seasoning at the table.",
    "brand": null
  },
  {
    "id": "grocery-009",
    "name": "Sunflower Oil",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Cooking Oils",
    "price": 5.49,
    "oldPrice": 6.29,
    "unit": "pack",
    "packageSize": "48 fl oz",
    "image": "/images/products/grocery-009.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "sunflower oil",
      "pantry",
      "cooking oils",
      "refined sunflower oil",
      "cooking",
      "sunflower",
      "oil"
    ],
    "description": "Neutral-flavored sunflower oil for frying, sautéing, baking, and dressings.",
    "brand": null
  },
  {
    "id": "grocery-010",
    "name": "Olive Oil",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Cooking Oils",
    "price": 6.24,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "17 fl oz",
    "image": "/images/products/grocery-010.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "olive oil",
      "pantry",
      "cooking oils",
      "cooking",
      "olive",
      "oil"
    ],
    "description": "Olive oil for sautéing, roasting, dressings, marinades, and finishing dishes.",
    "brand": null
  },
  {
    "id": "grocery-011",
    "name": "Semolina",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Baking",
    "price": 3.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "24 oz",
    "image": "/images/products/grocery-011.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "semolina",
      "pantry",
      "baking",
      "grains",
      "cooking"
    ],
    "description": "Coarsely milled durum wheat for pasta, baking, and puddings.",
    "brand": null
  },
  {
    "id": "grocery-012",
    "name": "Dried White Beans",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Beans & Legumes",
    "price": 1.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "1 lb bag",
    "image": "/images/products/grocery-012.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "dried white beans",
      "pantry",
      "beans & legumes",
      "grains & beans",
      "cooking",
      "dried",
      "beans",
      "white"
    ],
    "description": "Dried white beans for soups, stews, casseroles, salads, and side dishes.",
    "brand": null
  },
  {
    "id": "can-001",
    "name": "Canned Green Peas",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Canned Vegetables",
    "price": 0.78,
    "oldPrice": 0.98,
    "unit": "pack",
    "packageSize": "15 oz can",
    "image": "/images/products/can-001.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "canned green peas",
      "canned & jarred",
      "canned vegetables",
      "canned & jarred foods",
      "pantry",
      "canned food",
      "canned",
      "peas"
    ],
    "description": "Tender canned green peas ready for salads, soups, sides, and quick meals.",
    "brand": null
  },
  {
    "id": "can-002",
    "name": "Canned Sweet Corn",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Canned Vegetables",
    "price": 0.78,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "15 oz can",
    "image": "/images/products/can-002.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "canned sweet corn",
      "canned & jarred",
      "canned vegetables",
      "canned & jarred foods",
      "pantry",
      "canned food",
      "canned",
      "sweet"
    ],
    "description": "Sweet canned corn ready for salads, sides, soups, and quick meals.",
    "brand": null
  },
  {
    "id": "can-003",
    "name": "Canned Red Kidney Beans",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Canned Beans",
    "price": 0.88,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "15.5 oz can",
    "image": "/images/products/can-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "canned red kidney beans",
      "canned & jarred",
      "canned beans",
      "canned & jarred foods",
      "pantry",
      "canned food",
      "canned",
      "kidney"
    ],
    "description": "Canned red kidney beans ready for chili, soups, salads, and rice dishes.",
    "brand": null
  },
  {
    "id": "can-004",
    "name": "Dill Pickles",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Pickles & Preserves",
    "price": 2.92,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "32 fl oz jar",
    "image": "/images/products/can-004.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "dill pickles",
      "pickles",
      "pickled cucumbers",
      "jarred vegetables",
      "sandwiches"
    ],
    "description": "Crisp dill pickles for sandwiches, burgers, snacks, and sides.",
    "brand": null
  },
  {
    "id": "can-005",
    "name": "Pickled Tomatoes",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Pickles & Preserves",
    "price": 3.49,
    "oldPrice": 3.99,
    "unit": "pack",
    "packageSize": "24 oz jar",
    "image": "/images/products/can-005.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "pickled tomatoes",
      "canned & jarred",
      "pickles & preserves",
      "canned & jarred foods",
      "pickled vegetables",
      "pantry",
      "canned food",
      "pickled",
      "tomatoes"
    ],
    "description": "Tangy pickled tomatoes for appetizers, sandwiches, and savory sides.",
    "brand": null
  },
  {
    "id": "can-006",
    "name": "Smoked Sprats in Oil",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Canned Fish",
    "price": 3.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "5.6 oz can",
    "image": "/images/products/can-006.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "smoked sprats in oil",
      "canned & jarred",
      "canned fish",
      "canned & jarred foods",
      "sprats",
      "pantry",
      "canned food",
      "smoked",
      "oil"
    ],
    "description": "Smoky sprats packed in oil for appetizers, sandwiches, and savory snacks.",
    "brand": null
  },
  {
    "id": "can-007",
    "name": "Chunk Tuna",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Canned Fish",
    "price": 1.29,
    "oldPrice": 1.59,
    "unit": "pack",
    "packageSize": "5 oz can",
    "image": "/images/products/can-007.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "chunk tuna",
      "canned & jarred",
      "canned fish",
      "tuna chunks",
      "canned & jarred foods",
      "pantry",
      "canned food",
      "tuna",
      "chunks"
    ],
    "description": "Canned chunk tuna for sandwiches, salads, pasta, and quick meals.",
    "brand": null
  },
  {
    "id": "can-008",
    "name": "Liver Pâté",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Pâté & Spreads",
    "price": 3.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/can-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "liver pâté",
      "canned & jarred",
      "pâté & spreads",
      "canned & jarred foods",
      "canned meat & pâté",
      "pantry",
      "canned food",
      "liver"
    ],
    "description": "Savory liver pâté for toast, crackers, sandwiches, and appetizers.",
    "brand": null
  },
  {
    "id": "can-009",
    "name": "Zucchini Spread",
    "category": "Canned & Jarred",
    "categorySlug": "konservatsiia",
    "subcategory": "Vegetable Spreads",
    "price": 3.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 oz jar",
    "image": "/images/products/can-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "zucchini spread",
      "vegetable spread",
      "zucchini",
      "jarred food",
      "appetizer"
    ],
    "description": "Savory zucchini spread for toast, crackers, sandwiches, and appetizers.",
    "brand": null
  },
  {
    "id": "sauce-001",
    "name": "Tomato Paste",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Tomato Products",
    "price": 0.98,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "6 oz can",
    "image": "/images/products/sauce-001.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "tomato paste",
      "condiments & spices",
      "tomato products",
      "sauces, condiments & spices",
      "tomato",
      "paste"
    ],
    "description": "Concentrated tomato paste for sauces, soups, stews, and braises.",
    "brand": null
  },
  {
    "id": "sauce-002",
    "name": "Tomato Paste",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Tomato Products",
    "price": 1.69,
    "oldPrice": 1.99,
    "unit": "pack",
    "packageSize": "12 oz can",
    "image": "/images/products/sauce-002.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "tomato paste",
      "condiments & spices",
      "tomato products",
      "sauces, condiments & spices",
      "tomato",
      "paste"
    ],
    "description": "Concentrated tomato paste for sauces, soups, stews, and braises.",
    "brand": null
  },
  {
    "id": "sauce-003",
    "name": "Ketchup",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Ketchup",
    "price": 1.64,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "24 oz",
    "image": "/images/products/sauce-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "ketchup",
      "condiments & spices",
      "mild ketchup",
      "sauces, condiments & spices"
    ],
    "description": "Tomato ketchup for burgers, fries, sandwiches, and dipping.",
    "brand": null
  },
  {
    "id": "sauce-004",
    "name": "Mayonnaise",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Mayonnaise",
    "price": 2.97,
    "oldPrice": 3.47,
    "unit": "pack",
    "packageSize": "30 fl oz",
    "image": "/images/products/sauce-004.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "mayonnaise",
      "condiments & spices",
      "sauces, condiments & spices"
    ],
    "description": "Creamy mayonnaise for sandwiches, salads, dips, and everyday cooking.",
    "brand": null
  },
  {
    "id": "sauce-005",
    "name": "Hot Mustard",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Mustard",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/sauce-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "hot mustard",
      "mustard",
      "spicy mustard",
      "condiment",
      "sausages",
      "sandwiches"
    ],
    "description": "Sharp hot mustard for sausages, meats, sandwiches, and marinades.",
    "brand": null
  },
  {
    "id": "sauce-006",
    "name": "Ground Black Pepper",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Spices & Seasonings",
    "price": 3.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "3 oz",
    "image": "/images/products/sauce-006.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "ground black pepper",
      "condiments & spices",
      "spices & seasonings",
      "sauces, condiments & spices",
      "black",
      "pepper",
      "ground"
    ],
    "description": "Ground black pepper for seasoning meats, vegetables, sauces, and everyday dishes.",
    "brand": null
  },
  {
    "id": "sauce-007",
    "name": "Bay Leaves",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Spices & Seasonings",
    "price": 1.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "0.5 oz",
    "image": "/images/products/sauce-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "bay leaves",
      "condiments & spices",
      "spices & seasonings",
      "sauces, condiments & spices",
      "bay",
      "leaves"
    ],
    "description": "Whole dried bay leaves for soups, stews, sauces, and braises.",
    "brand": null
  },
  {
    "id": "sauce-008",
    "name": "Chicken Seasoning",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Spices & Seasonings",
    "price": 1.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "2.5 oz",
    "image": "/images/products/sauce-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "chicken seasoning",
      "condiments & spices",
      "spices & seasonings",
      "chicken seasoning blend",
      "sauces, condiments & spices",
      "chicken",
      "blend",
      "seasoning"
    ],
    "description": "Savory seasoning blend for chicken, poultry dishes, roasted vegetables, and marinades.",
    "brand": null
  },
  {
    "id": "sauce-009",
    "name": "Soy Sauce",
    "category": "Condiments & Spices",
    "categorySlug": "sousy-spetsii",
    "subcategory": "Sauces",
    "price": 1.79,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "15 fl oz",
    "image": "/images/products/sauce-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "soy sauce",
      "condiments & spices",
      "soy",
      "sauce"
    ],
    "description": "Soy sauce for stir-fries, marinades, dipping, and seasoning.",
    "brand": null
  },
  {
    "id": "drink-001",
    "name": "Bottled Water",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Water",
    "price": 1.29,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "1.5 L",
    "image": "/images/products/drink-001.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "bottled water",
      "beverages",
      "water",
      "still water",
      "drinks",
      "still",
      "bottled"
    ],
    "description": "Bottled still water for everyday hydration.",
    "brand": null
  },
  {
    "id": "drink-002",
    "name": "Sparkling Mineral Water",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Water",
    "price": 1.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "1 L",
    "image": "/images/products/drink-002.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "sparkling mineral water",
      "beverages",
      "water",
      "drinks",
      "sparkling",
      "mineral"
    ],
    "description": "Sparkling mineral water for everyday drinking and serving with meals.",
    "brand": null
  },
  {
    "id": "drink-003",
    "name": "Apple Juice",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Juice",
    "price": 2.27,
    "oldPrice": 2.79,
    "unit": "pack",
    "packageSize": "64 fl oz",
    "image": "/images/products/drink-003.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "apple juice",
      "beverages",
      "juice",
      "drinks",
      "apple"
    ],
    "description": "Apple juice with a crisp fruit flavor for breakfast and everyday drinking.",
    "brand": null
  },
  {
    "id": "drink-004",
    "name": "Mixed Fruit Juice",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Juice",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "64 fl oz",
    "image": "/images/products/drink-004.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "mixed fruit juice",
      "beverages",
      "juice",
      "drinks",
      "fruit",
      "mixed"
    ],
    "description": "Mixed fruit juice for breakfast, snacks, and everyday drinking.",
    "brand": null
  },
  {
    "id": "drink-005",
    "name": "Black Tea",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Tea",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "20 ct",
    "image": "/images/products/drink-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "black tea",
      "beverages",
      "tea",
      "drinks",
      "black"
    ],
    "description": "Black tea bags for hot tea, iced tea, and everyday brewing.",
    "brand": null
  },
  {
    "id": "drink-006",
    "name": "Green Tea",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Tea",
    "price": 2.69,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "20 ct",
    "image": "/images/products/drink-006.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "green tea",
      "beverages",
      "tea",
      "drinks",
      "green"
    ],
    "description": "Green tea bags for hot tea, iced tea, and everyday brewing.",
    "brand": null
  },
  {
    "id": "drink-007",
    "name": "Instant Coffee",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Coffee",
    "price": 8.88,
    "oldPrice": 9.98,
    "unit": "pack",
    "packageSize": "12 oz",
    "image": "/images/products/drink-007.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "instant coffee",
      "beverages",
      "coffee",
      "drinks",
      "instant"
    ],
    "description": "Instant coffee for a quick cup at home, at work, or on the go.",
    "brand": null
  },
  {
    "id": "drink-008",
    "name": "Ground Coffee",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Coffee",
    "price": 6.44,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "12 oz",
    "image": "/images/products/drink-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "ground coffee",
      "beverages",
      "coffee",
      "drinks",
      "ground"
    ],
    "description": "Ground coffee for drip coffee makers and everyday brewing.",
    "brand": null
  },
  {
    "id": "drink-009",
    "name": "Lemon Soda",
    "category": "Beverages",
    "categorySlug": "napoi",
    "subcategory": "Soda",
    "price": 1.56,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "2 L",
    "image": "/images/products/drink-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "lemon soda",
      "beverages",
      "soda",
      "drinks",
      "lemon"
    ],
    "description": "Lemon-flavored soda with a bright citrus taste, served chilled.",
    "brand": null
  },
  {
    "id": "drink-010",
    "name": "Cocoa Powder",
    "category": "Pantry",
    "categorySlug": "bakaliia",
    "subcategory": "Baking",
    "price": 3.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/drink-010.jpg",
    "inStock": false,
    "isPromo": false,
    "tags": [
      "cocoa powder",
      "pantry",
      "baking",
      "powder"
    ],
    "description": "Cocoa powder for baking, hot cocoa, desserts, and chocolate sauces.",
    "brand": null
  },
  {
    "id": "sweet-001",
    "name": "Milk Chocolate",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Chocolate",
    "price": 1.49,
    "oldPrice": 1.79,
    "unit": "pack",
    "packageSize": "3.5 oz",
    "image": "/images/products/sweet-001.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "milk chocolate",
      "snacks & candy",
      "chocolate",
      "milk"
    ],
    "description": "Smooth milk chocolate for snacking, sharing, and desserts.",
    "brand": null
  },
  {
    "id": "sweet-002",
    "name": "Dark Chocolate",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Chocolate",
    "price": 1.79,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "3.5 oz",
    "image": "/images/products/sweet-002.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "dark chocolate",
      "snacks & candy",
      "chocolate",
      "dark"
    ],
    "description": "Rich dark chocolate for snacking, sharing, and desserts.",
    "brand": null
  },
  {
    "id": "sweet-003",
    "name": "Sugar Cookies",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Cookies",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "12 oz",
    "image": "/images/products/sweet-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "sugar cookies",
      "snacks & candy",
      "cookies",
      "sugar"
    ],
    "description": "Crisp, sweet sugar cookies for snacks, lunchboxes, and dessert trays.",
    "brand": null
  },
  {
    "id": "sweet-004",
    "name": "Oatmeal Cookies",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Cookies",
    "price": 3.23,
    "oldPrice": 3.69,
    "unit": "pack",
    "packageSize": "18 oz",
    "image": "/images/products/sweet-004.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "oatmeal cookies",
      "snacks & candy",
      "cookies",
      "oatmeal"
    ],
    "description": "Oatmeal cookies with a hearty oat texture for snacks and dessert.",
    "brand": null
  },
  {
    "id": "sweet-005",
    "name": "Cream-Filled Wafers",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Wafers",
    "price": 1.97,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/sweet-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "cream-filled wafers",
      "snacks & candy",
      "wafers",
      "cream-filled",
      "cream"
    ],
    "description": "Crisp wafer cookies layered with a sweet cream filling.",
    "brand": null
  },
  {
    "id": "sweet-006",
    "name": "Assorted Chocolates",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Candy",
    "price": 8.99,
    "oldPrice": 10.49,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/sweet-006.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "assorted chocolates",
      "snacks & candy",
      "candy",
      "chocolates",
      "assorted"
    ],
    "description": "Assorted chocolate candies for sharing, gifting, and dessert trays.",
    "brand": null
  },
  {
    "id": "sweet-007",
    "name": "Pink & White Zefir Marshmallows",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Specialty Candy",
    "price": 4.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "10.5 oz",
    "image": "/images/products/sweet-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "pink & white zefir marshmallows",
      "zefir",
      "confection",
      "sweet treat",
      "white zefir",
      "pink zefir"
    ],
    "description": "Soft, airy zefir confections in pink and white pieces.",
    "brand": null
  },
  {
    "id": "sweet-008",
    "name": "Fruit Jelly Candies",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Fruit Candy",
    "price": 2.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "8 oz",
    "image": "/images/products/sweet-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "fruit jelly candies",
      "snacks & candy",
      "fruit candy",
      "fruit gummies",
      "fruit",
      "jelly",
      "candies",
      "jellies"
    ],
    "description": "Soft fruit-flavored jelly candies for snacking and sharing.",
    "brand": null
  },
  {
    "id": "sweet-009",
    "name": "Salted Crackers",
    "category": "Snacks & Candy",
    "categorySlug": "solodoshchi",
    "subcategory": "Crackers",
    "price": 1.98,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/sweet-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "salted crackers",
      "snacks & candy",
      "crackers",
      "crackers & snacks",
      "salted"
    ],
    "description": "Crisp salted crackers for snacks, soups, cheese boards, and dips.",
    "brand": null
  },
  {
    "id": "frozen-001",
    "name": "Frozen Mixed Vegetables",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Frozen Vegetables",
    "price": 1.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "12 oz",
    "image": "/images/products/frozen-001.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "frozen mixed vegetables",
      "frozen foods",
      "frozen vegetables",
      "frozen vegetable mix",
      "vegetables",
      "vegetable",
      "mix",
      "mixed"
    ],
    "description": "A convenient frozen vegetable blend for sides, soups, stir-fries, and quick meals.",
    "brand": null
  },
  {
    "id": "frozen-002",
    "name": "Frozen Green Peas",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Frozen Vegetables",
    "price": 1.29,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "12 oz",
    "image": "/images/products/frozen-002.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "frozen green peas",
      "frozen foods",
      "frozen vegetables",
      "vegetables",
      "peas",
      "green"
    ],
    "description": "Frozen green peas for sides, soups, rice dishes, and quick meals.",
    "brand": null
  },
  {
    "id": "frozen-003",
    "name": "Meat Pelmeni Dumplings",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Frozen Meals & Dumplings",
    "price": 7.99,
    "oldPrice": 9.49,
    "unit": "pack",
    "packageSize": "32 oz",
    "image": "/images/products/frozen-003.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "meat pelmeni dumplings",
      "pelmeni",
      "meat dumplings",
      "dumplings",
      "frozen meal"
    ],
    "description": "Frozen meat-filled pelmeni dumplings ready to boil for a quick meal.",
    "brand": null
  },
  {
    "id": "frozen-004",
    "name": "Potato Varenyky",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Frozen Meals & Dumplings",
    "price": 5.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "32 oz",
    "image": "/images/products/frozen-004.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "potato varenyky",
      "varenyky",
      "potato dumplings",
      "dumplings",
      "frozen meal"
    ],
    "description": "Frozen potato-filled varenyky ready to boil and serve with sour cream.",
    "brand": null
  },
  {
    "id": "frozen-005",
    "name": "Salami Pizza",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Pizza",
    "price": 3.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "12 oz",
    "image": "/images/products/frozen-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "salami pizza",
      "frozen foods",
      "pizza",
      "frozen salami pizza",
      "frozen pizza",
      "salami"
    ],
    "description": "Frozen salami pizza for a quick lunch, dinner, or snack.",
    "brand": null
  },
  {
    "id": "frozen-006",
    "name": "Plombir Ice Cream",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Ice Cream",
    "price": 4.99,
    "oldPrice": 5.99,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/frozen-006.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "plombir ice cream",
      "plombir",
      "ice cream",
      "frozen dessert"
    ],
    "description": "Rich, creamy ice cream inspired by the classic plombir recipe.",
    "brand": null
  },
  {
    "id": "frozen-007",
    "name": "Frozen Hake",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Seafood",
    "price": 8.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "2 lb",
    "image": "/images/products/frozen-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "frozen hake",
      "frozen foods",
      "seafood",
      "frozen fish",
      "hake",
      "frozen"
    ],
    "description": "Frozen hake for baking, pan-frying, soups, and seafood dishes.",
    "brand": null
  },
  {
    "id": "frozen-008",
    "name": "Frozen Chicken Cutlets",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Frozen Prepared Foods",
    "price": 5.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "24 oz",
    "image": "/images/products/frozen-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "frozen chicken cutlets",
      "frozen foods",
      "frozen prepared foods",
      "chicken",
      "cutlets"
    ],
    "description": "Frozen chicken cutlets ready to cook for sandwiches, plates, and quick meals.",
    "brand": null
  },
  {
    "id": "frozen-009",
    "name": "Farmer Cheese Blintzes",
    "category": "Frozen Foods",
    "categorySlug": "zamorozheni",
    "subcategory": "Frozen Meals & Dumplings",
    "price": 5.49,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 oz",
    "image": "/images/products/frozen-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "farmer cheese blintzes",
      "cheese blintzes",
      "blintzes",
      "farmer cheese",
      "frozen breakfast"
    ],
    "description": "Frozen blintzes filled with farmer cheese for breakfast or dessert.",
    "brand": null
  },
  {
    "id": "house-001",
    "name": "Lemon-Scented Dish Soap",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Dish Soap",
    "price": 1.94,
    "oldPrice": 2.24,
    "unit": "pack",
    "packageSize": "28 fl oz",
    "image": "/images/products/house-001.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "lemon-scented dish soap",
      "cleaning & laundry",
      "dish soap",
      "home care & cleaning",
      "dish care",
      "cleaning",
      "lemon",
      "dish",
      "soap"
    ],
    "description": "Lemon-scented dish soap for hand-washing dishes, glasses, cookware, and utensils.",
    "brand": null
  },
  {
    "id": "house-002",
    "name": "Dish Soap",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Dish Soap",
    "price": 5.38,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "90 fl oz",
    "image": "/images/products/house-002.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "dish soap",
      "cleaning & laundry",
      "home care & cleaning",
      "dish care",
      "cleaning",
      "dish",
      "soap"
    ],
    "description": "Liquid dish soap for hand-washing dishes, glasses, cookware, and utensils.",
    "brand": null
  },
  {
    "id": "house-003",
    "name": "Floor Cleaner",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Floor Care",
    "price": 4.99,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "48 fl oz",
    "image": "/images/products/house-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "floor cleaner",
      "cleaning & laundry",
      "floor care",
      "all-purpose floor cleaner",
      "home care & cleaning",
      "floor cleaners",
      "cleaning",
      "all-purpose",
      "floor"
    ],
    "description": "Floor cleaner for routine cleaning of washable hard floors.",
    "brand": null
  },
  {
    "id": "house-004",
    "name": "Kitchen Degreaser",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Kitchen Cleaners",
    "price": 4.98,
    "oldPrice": 5.48,
    "unit": "pack",
    "packageSize": "32 fl oz",
    "image": "/images/products/house-004.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "kitchen degreaser",
      "cleaning & laundry",
      "kitchen cleaners",
      "home care & cleaning",
      "cleaning",
      "kitchen",
      "degreaser"
    ],
    "description": "Kitchen degreaser for cutting through grease on stovetops, counters, and other washable kitchen surfaces.",
    "brand": null
  },
  {
    "id": "house-005",
    "name": "Bathroom Cleaner",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Bathroom Cleaners",
    "price": 3.98,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "32 fl oz",
    "image": "/images/products/house-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "bathroom cleaner",
      "cleaning & laundry",
      "bathroom cleaners",
      "home care & cleaning",
      "cleaning",
      "bathroom",
      "cleaner"
    ],
    "description": "Bathroom cleaner for sinks, tubs, tile, and other washable bathroom surfaces.",
    "brand": null
  },
  {
    "id": "house-006",
    "name": "Pine-Scented Toilet Bowl Cleaner",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Bathroom Cleaners",
    "price": 1.98,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "24 fl oz",
    "image": "/images/products/house-006.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "pine-scented toilet bowl cleaner",
      "cleaning & laundry",
      "bathroom cleaners",
      "home care & cleaning",
      "toilet cleaners",
      "cleaning",
      "pine-scented",
      "toilet"
    ],
    "description": "Pine-scented toilet bowl cleaner for routine bathroom cleaning.",
    "brand": null
  },
  {
    "id": "house-007",
    "name": "Powder Laundry Detergent",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Laundry",
    "price": 9.98,
    "oldPrice": 11.48,
    "unit": "pack",
    "packageSize": "5 lb",
    "image": "/images/products/house-007.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "powder laundry detergent",
      "cleaning & laundry",
      "laundry",
      "home care & cleaning",
      "laundry care",
      "cleaning",
      "powder",
      "detergent"
    ],
    "description": "Powder laundry detergent for everyday machine-washing of clothes and household fabrics.",
    "brand": null
  },
  {
    "id": "house-008",
    "name": "Fabric Softener",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Laundry",
    "price": 5.48,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "64 fl oz",
    "image": "/images/products/house-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "fabric softener",
      "cleaning & laundry",
      "laundry",
      "home care & cleaning",
      "laundry care",
      "cleaning",
      "fabric",
      "softener"
    ],
    "description": "Liquid fabric softener for softer fabrics and fresh-smelling laundry.",
    "brand": null
  },
  {
    "id": "house-009",
    "name": "Liquid Hand Soap",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Hand Soap",
    "price": 1.48,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "16 fl oz",
    "image": "/images/products/house-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "liquid hand soap",
      "cleaning & laundry",
      "hand soap",
      "home care & cleaning",
      "household hygiene",
      "cleaning",
      "liquid",
      "hand",
      "soap"
    ],
    "description": "Liquid hand soap for routine handwashing at sinks and wash areas.",
    "brand": null
  },
  {
    "id": "house-010",
    "name": "Toilet Paper",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Paper Goods",
    "price": 7.98,
    "oldPrice": 8.98,
    "unit": "pack",
    "packageSize": "8 rolls",
    "image": "/images/products/house-010.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "toilet paper",
      "household essentials",
      "paper goods",
      "home care & cleaning",
      "household hygiene",
      "cleaning",
      "toilet",
      "paper"
    ],
    "description": "Everyday toilet paper in an 8-roll pack.",
    "brand": null
  },
  {
    "id": "house-011",
    "name": "Glass Cleaner",
    "category": "Cleaning & Laundry",
    "categorySlug": "pobutova-khimiia",
    "subcategory": "Glass Cleaners",
    "price": 3.48,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "32 fl oz",
    "image": "/images/products/house-011.jpg",
    "inStock": false,
    "isPromo": false,
    "tags": [
      "glass cleaner",
      "cleaning & laundry",
      "glass cleaners",
      "home care & cleaning",
      "cleaning",
      "glass",
      "cleaner"
    ],
    "description": "Glass cleaner for windows, mirrors, and other washable glass surfaces.",
    "brand": null
  },
  {
    "id": "clean-001",
    "name": "Kitchen Sponges",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Sponges",
    "price": 2.98,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "6 ct",
    "image": "/images/products/clean-001.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "kitchen sponges",
      "household essentials",
      "sponges",
      "household supplies",
      "kitchen"
    ],
    "description": "Kitchen sponges for washing dishes and wiping kitchen surfaces.",
    "brand": null
  },
  {
    "id": "clean-002",
    "name": "Cleaning Wipes",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Wipes & Cloths",
    "price": 4.48,
    "oldPrice": 5.28,
    "unit": "pack",
    "packageSize": "75 ct",
    "image": "/images/products/clean-002.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "cleaning wipes",
      "household essentials",
      "wipes & cloths",
      "all-purpose cleaning wipes",
      "household supplies",
      "cleaning cloths & wipes",
      "all-purpose",
      "cleaning",
      "wipes"
    ],
    "description": "Disposable cleaning wipes for quick cleanup of hard household surfaces.",
    "brand": null
  },
  {
    "id": "clean-003",
    "name": "Reusable Cleaning Cloths",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Wipes & Cloths",
    "price": 3.48,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "3 ct",
    "image": "/images/products/clean-003.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "reusable cleaning cloths",
      "household essentials",
      "wipes & cloths",
      "viscose cleaning cloths",
      "household supplies",
      "cleaning cloths & wipes",
      "viscose",
      "cleaning",
      "cloths"
    ],
    "description": "Reusable cleaning cloths for kitchens, bathrooms, and everyday surfaces.",
    "brand": null
  },
  {
    "id": "clean-004",
    "name": "Rubber Cleaning Gloves",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Cleaning Gloves",
    "price": 2.98,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 pair",
    "image": "/images/products/clean-004.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "rubber cleaning gloves",
      "household essentials",
      "cleaning gloves",
      "household cleaning gloves",
      "household supplies",
      "cleaning",
      "gloves",
      "rubber"
    ],
    "description": "Reusable rubber gloves for dishwashing and household cleaning.",
    "brand": null
  },
  {
    "id": "clean-005",
    "name": "13-Gallon Trash Bags",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Trash Bags",
    "price": 5.48,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "13 gal, 30 ct",
    "image": "/images/products/clean-005.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "13-gallon trash bags",
      "household essentials",
      "household supplies",
      "garbage bags",
      "trash",
      "bags",
      "trash bags"
    ],
    "description": "Trash bags sized for standard 13-gallon kitchen cans.",
    "brand": null
  },
  {
    "id": "clean-006",
    "name": "30-Gallon Trash Bags",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Trash Bags",
    "price": 7.48,
    "oldPrice": 8.48,
    "unit": "pack",
    "packageSize": "30 gal, 20 ct",
    "image": "/images/products/clean-006.jpg",
    "inStock": true,
    "isPromo": true,
    "tags": [
      "30-gallon trash bags",
      "household essentials",
      "household supplies",
      "garbage bags",
      "trash",
      "bags",
      "trash bags"
    ],
    "description": "Large trash bags for 30-gallon cans and heavier household cleanup.",
    "brand": null
  },
  {
    "id": "clean-007",
    "name": "Paper Towels",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Paper Towels",
    "price": 4.48,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "2 rolls",
    "image": "/images/products/clean-007.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "paper towels",
      "household essentials",
      "household supplies",
      "paper",
      "towels"
    ],
    "description": "Paper towels for spills, kitchen cleanup, and everyday household use.",
    "brand": null
  },
  {
    "id": "clean-008",
    "name": "Microfiber Mop",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Cleaning Tools",
    "price": 12.98,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 ct",
    "image": "/images/products/clean-008.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "microfiber mop",
      "household essentials",
      "cleaning tools",
      "household supplies",
      "microfiber",
      "mop"
    ],
    "description": "Microfiber mop for routine cleaning of hard floors.",
    "brand": null
  },
  {
    "id": "clean-009",
    "name": "Cleaning Bucket",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Cleaning Tools",
    "price": 5.98,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "3 gal",
    "image": "/images/products/clean-009.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "cleaning bucket",
      "household essentials",
      "cleaning tools",
      "plastic bucket",
      "household supplies",
      "plastic",
      "bucket",
      "cleaning"
    ],
    "description": "Durable cleaning bucket for mopping, rinsing, and household chores.",
    "brand": null
  },
  {
    "id": "clean-010",
    "name": "Plastic Wrap",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Food Storage & Wraps",
    "price": 2.24,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "200 sq ft",
    "image": "/images/products/clean-010.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "plastic wrap",
      "household essentials",
      "food storage & wraps",
      "household supplies",
      "plastic",
      "wrap"
    ],
    "description": "Plastic wrap for covering food, wrapping leftovers, and kitchen prep.",
    "brand": null
  },
  {
    "id": "clean-011",
    "name": "Aluminum Foil",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Food Storage & Wraps",
    "price": 5.12,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "75 sq ft",
    "image": "/images/products/clean-011.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "aluminum foil",
      "household essentials",
      "food storage & wraps",
      "household supplies",
      "aluminum",
      "foil"
    ],
    "description": "Aluminum foil for wrapping, covering, baking, and food prep.",
    "brand": null
  },
  {
    "id": "clean-012",
    "name": "Food Storage Bags",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Food Storage & Wraps",
    "price": 2.72,
    "oldPrice": null,
    "unit": "pack",
    "packageSize": "100 ct",
    "image": "/images/products/clean-012.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "food storage bags",
      "household essentials",
      "food storage & wraps",
      "household supplies",
      "storage bags",
      "food",
      "storage",
      "bags"
    ],
    "description": "Food storage bags for leftovers, snacks, meal prep, and pantry organization.",
    "brand": null
  },
  {
    "id": "clean-013",
    "name": "Scrub Brush",
    "category": "Household Essentials",
    "categorySlug": "tovary-dlia-prybyrannia",
    "subcategory": "Cleaning Tools",
    "price": 3.98,
    "oldPrice": null,
    "unit": "pcs",
    "packageSize": "1 ct",
    "image": "/images/products/clean-013.jpg",
    "inStock": true,
    "isPromo": false,
    "tags": [
      "scrub brush",
      "household essentials",
      "cleaning tools",
      "kitchen cleaning brush",
      "household supplies",
      "kitchen",
      "cleaning",
      "brush",
      "scrub"
    ],
    "description": "Handheld scrub brush for sinks, counters, tile, and other hard surfaces.",
    "brand": null
  }
];
